V030
StillGreen-san/SalienBot pull request #16
Opened 2018-06-30 10:36 UTC by DisturbedII

added #13 
added #3

2018-06-30 11:25 UTC, StillGreen-san requested changes
some more work to be done

2018-06-30 11:25 UTC, StillGreen-san commented on SalienBot/Program.cs
> +                File.Create("access_token.txt");
File write functions should have an option to create the file if it doesn't exist.
No need for if()

2018-06-30 11:25 UTC, StillGreen-san commented on SalienBot/Program.cs
> -            ACCESS_TOKEN.Trim('"', ' ', ',');
Had moved the .Trimm() part down here to catch both file and console input.

2018-06-30 11:25 UTC, StillGreen-san commented on SalienBot/Program.cs
> +                ACCESS_TOKEN = line.Trim(' ','"',',','.');
.Trimm() should be moved down. See comment below.

2018-06-30 11:25 UTC, StillGreen-san commented on SalienBot/Program.cs
> +                            if (split[0] == "ROUND_TIME")
Using Switch recommended, if only for the cleaner looks.

2018-06-30 11:25 UTC, StillGreen-san commented on SalienBot/Program.cs
> +       /* public static void refreshPrioritiesConfig()
Can be removed if the new logic works.

2018-06-30 11:25 UTC, StillGreen-san commented on SalienBot/Program.cs
> +                ExceptionHandling(e);
ExceptionHandling is currently not designed to handle those exceptions. As it automatically prints countdown for retry, but here is nothing to retry.
Also for this one, there is no handling required as the value might be empty, which isn't an error.

2018-06-30 11:25 UTC, StillGreen-san commented on SalienBot/Program.cs
> +                Console.WriteLine(e);
Have you tried this? Not sure if .ToString() is needed for this one.

2018-06-30 12:15 UTC, DisturbedII commented
fixes are comitted

2018-07-01 10:53 UTC, StillGreen-san approved these changes

2018-07-01 10:54 UTC, merged